DELIMITER &
CREATE FUNCTION FN_FORMATEAR_NOMBRES (P_NOMBRE VARCHAR(200), P_TIPO_FORMATO VARCHAR(10))
RETURNS VARCHAR (200)
-- Se debe colocar esto para que permita la creacion de funciones
DETERMINISTIC
READS SQL DATA

BEGIN
	DECLARE V_NOMBRE		VARCHAR (200) ;
    
    IF P_TIPO_FORMATO ='MAY' THEN
    
		SET V_NOMBRE = UPPER(P_NOMBRE);
    
    ELSEIF P_TIPO_FORMATO ='MIN' THEN
    
		SET V_NOMBRE = LOWER(P_NOMBRE);
        
	ELSEIF P_TIPO_FORMATO ='NOR' THEN
    
		SET V_NOMBRE = CONCAT(UPPER(SUBSTRING(P_NOMBRE,1,1)),LOWER(SUBSTRING(P_NOMBRE,2)));
    
    END IF;
    
    
RETURN V_NOMBRE;
END &