DELIMITER &
CREATE PROCEDURE PR_ELIMINAR_EVENTO( P_NOMBRE_EVENTO VARCHAR (60))

BEGIN
	-- Declarar variables
    DECLARE V_ESTADO 		VARCHAR (30) DEFAULT 'INACTIVO';
    DECLARE V_ID_EVENTO 	INT;
	
    -- Sacar id del evento
    SELECT ID_EVENTO INTO V_ID_EVENTO FROM EVENTO WHERE TIPO_DE_EVENTO = P_NOMBRE_EVENTO;
    
    -- Elimina registro de la tabla usuario sistema
    UPDATE EVENTO SET ESTADO = V_ESTADO WHERE TIPO_DE_EVENTO = P_NOMBRE_EVENTO;
    
    -- Se Inactiva el registro de los paquetes(todos)
    UPDATE PAQUETE SET ESTADO = V_ESTADO WHERE EVENTOID_EVENTO = V_ID_EVENTO;
    
    
END &
