SELECT 	 D.ID_EVENTO
		,D.TIPO_DE_EVENTO
		,A.ID_PAQUETE
		,A.TIPO_DE_PAQUETE
        ,C.ID_INVENTARIO
        ,C.INVENTARIO
        ,B.CANTIDAD
        ,B.VALOR_SIN_IVA
        ,B.IVA
        ,B.VALOR_TOTAL
FROM PAQUETE A
INNER JOIN INVENTARIO_PAQUETE	AS B	ON A.ID_PAQUETE						= B.PAQUETEID_PAQUETE
INNER JOIN INVENTARIO			AS C	ON B.INVENTARIOID_INVENTARIO		= C.ID_INVENTARIO
INNER JOIN EVENTO				AS D	ON A.EVENTOID_EVENTO 				= D.ID_EVENTO
WHERE A.ESTADO ='ACTIVO'
ORDER BY ID_EVENTO ASC
;

DELIMITER &
CREATE PROCEDURE PR_CREAR_PAQUETES( 
	  P_PAQUETE_IDPAQUETE 	INT
    , P_CIUDAD 				VARCHAR (60)
)

BEGIN
	
    -- Declarar variables
    DECLARE V_ID_PAQUETE	 				INT;
    
    -- INSERTAR 

    
END &
