DELIMITER &
CREATE PROCEDURE PR_CREAR_INVENTARIO( 
	 P_INVENTARIO		VARCHAR (50)
	,P_CANTIDAD			INT
    ,P_VALOR_SIN_IVA	INT
    ,P_CATEGORIA		VARCHAR (50)
)

BEGIN
	
    -- Declarar variables
    DECLARE V_INVENTARIO		VARCHAR (50) DEFAULT UPPER(P_INVENTARIO);
    DECLARE V_VALOR_SIN_IVA 	INT DEFAULT	ROUND(P_VALOR_SIN_IVA);
    DECLARE V_VALOR_TOTAL 		INT DEFAULT ROUND(V_VALOR_SIN_IVA * 1.19);
	DECLARE V_IVA				INT DEFAULT V_VALOR_TOTAL - V_VALOR_SIN_IVA;
	DECLARE V_CATEGORIA 		VARCHAR (50) DEFAULT UPPER(P_CATEGORIA);
    DECLARE V_ESTADO			VARCHAR (30) DEFAULT 'ACTIVO';
    DECLARE V_INVENTARIO_NUEVO  VARCHAR (50); 
    
    SELECT INVENTARIO_NUEVO INTO V_INVENTARIO_NUEVO FROM(SELECT CONCAT(SUBSTRING(V_INVENTARIO,1,1),LOWER(SUBSTRING(V_INVENTARIO,2))) AS INVENTARIO_NUEVO) AS INVENTARIO;
    
   -- Insertar Inventario
   INSERT INTO Inventario( Inventario, Cantidad, Valor_sin_iva, Iva, Valor_Total, Categoria, Estado)
   VALUES
   (V_INVENTARIO_NUEVO, P_CANTIDAD, V_VALOR_SIN_IVA, V_IVA, V_VALOR_TOTAL, V_CATEGORIA, V_ESTADO)
   ;
    
END &
