DELIMITER &
CREATE PROCEDURE PR_OBTENER_ULTIMO_PAQUETE( 
    P_EVENTO 			VARCHAR (60)
)

BEGIN

SELECT 	MAX(TIPO_DE_PAQUETE) ULTIMO_PAQUETE
		,COUNT(*) CANTIDAD
FROM PAQUETE		AS A
INNER JOIN EVENTO 	AS B ON A.EVENTOID_EVENTO	=	B.ID_EVENTO
WHERE B.TIPO_DE_EVENTO = P_EVENTO
;

END &