DELIMITER &
CREATE PROCEDURE PR_ACTUALIZAR_EVENTO( 
	P_ID_EVENTO 		INT
	,P_NOMBRE_EVENTO 	VARCHAR (50)
    , P_TIPO_IMAGEN		VARCHAR (30)
    , P_IMAGEN 			VARCHAR (60)
)

BEGIN
	 -- Declarar variables
    DECLARE V_ID_EVENTO	INT;
    DECLARE V_CANTIDAD_EVENTO	INT;
    DECLARE V_NOMBRE_EVENTO VARCHAR (50);
    
    -- VALIDAR SI YA EXISTE EL EVENTO
    SELECT COUNT(*) INTO V_CANTIDAD_EVENTO FROM EVENTO WHERE TIPO_DE_EVENTO = P_NOMBRE_EVENTO;
    
    -- VALIDAR ID EVENTO
    SELECT ID_EVENTO INTO V_ID_EVENTO FROM EVENTO WHERE TIPO_DE_EVENTO = P_NOMBRE_EVENTO;
    
    -- FORMATEAR NOMBRE
    SELECT FN_FORMATEAR_NOMBRES(P_NOMBRE_EVENTO,'NOR') INTO V_NOMBRE_EVENTO;
    
    IF V_CANTIDAD_EVENTO = 0 OR V_ID_EVENTO = P_ID_EVENTO THEN
    
		-- Actualizar registro de la tabla evento
		UPDATE EVENTO 
        SET TIPO_DE_EVENTO = P_NOMBRE_EVENTO 
			,TIPO_IMAGEN = P_TIPO_IMAGEN
            ,IMAGEN = P_IMAGEN
		WHERE ID_EVENTO = P_ID_EVENTO;
    
    END IF;
    
END &
