DELIMITER &
CREATE PROCEDURE PR_ACTUALIZAR_EMPLEADO( P_ID_EMPLEADO INT, P_PRIMER_NOMBRE VARCHAR (40), P_SEGUNDO_NOMBRE VARCHAR (40), P_PRIMER_APELLIDO VARCHAR (40), P_SEGUNDO_APELLIDO VARCHAR (40),
P_TIPO_DOCUMENTOID_DOCUMENTO VARCHAR(10), P_NUMERO_DOCUMENTO VARCHAR (20), P_CARGOID_CARGO VARCHAR (50), P_EDAD INT (5), P_TELEFONO BIGINT (20), P_DIRECCION VARCHAR (50), P_EMAIL  VARCHAR (50), P_ROLID_ROL VARCHAR(50))

BEGIN
    -- Declarar variables
    DECLARE V_PRIMER_NOMBRE 				VARCHAR (50) DEFAULT UPPER(P_PRIMER_NOMBRE);
    DECLARE V_SEGUNDO_NOMBRE 				VARCHAR (40) DEFAULT UPPER(P_SEGUNDO_NOMBRE); 
    DECLARE V_PRIMER_APELLIDO 				VARCHAR (40) DEFAULT UPPER(P_PRIMER_APELLIDO);
    DECLARE V_SEGUNDO_APELLIDO 				VARCHAR (40) DEFAULT UPPER(P_SEGUNDO_APELLIDO);
	DECLARE V_TIPO_DOCUMENTOID_DOCUMENTO 	VARCHAR	(10) ;
    DECLARE V_NUMERO_DOCUMENTO 				VARCHAR (20) DEFAULT UPPER(P_NUMERO_DOCUMENTO);
    DECLARE V_CARGOID_CARGO 				INT 	(5)  ; 
    DECLARE V_EDAD 							INT 	(5)  DEFAULT UPPER(P_EDAD);
    DECLARE V_TELEFONO 						BIGINT	(20) DEFAULT UPPER(P_TELEFONO);
    DECLARE V_DIRECCION 					VARCHAR (50) DEFAULT UPPER(P_DIRECCION); 
    DECLARE V_EMAIL  						VARCHAR (50) DEFAULT UPPER(P_EMAIL);
    DECLARE V_ROLID_ROL  					INT		(15) ;
	
    -- Obtener Id del documento enviado
    SELECT ID_DOCUMENTO INTO V_TIPO_DOCUMENTOID_DOCUMENTO FROM(SELECT ID_DOCUMENTO FROM TIPO_DOCUMENTO WHERE SIGLAS = P_TIPO_DOCUMENTOID_DOCUMENTO) AS ID_DOCUMENTO;
    
    -- Obtener Id del cargo enviado
    SELECT ID_CARGO INTO V_CARGOID_CARGO FROM(SELECT ID_CARGO FROM CARGO WHERE NOMBRE_DE_CARGO =P_CARGOID_CARGO) AS ID_CARGO;
    
    -- Obtener Id del rol enviado
    SELECT ID_ROL INTO V_ROLID_ROL FROM(SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL =P_ROLID_ROL) AS ID_ROL;
    
    -- Editar registro de la tabla usuario sistema
    UPDATE EMPLEADO 							
		SET   PRIMER_NOMBRE 				=	V_PRIMER_NOMBRE
			, SEGUNDO_NOMBRE 				=	V_SEGUNDO_NOMBRE
			, PRIMER_APELLIDO 				=	V_PRIMER_APELLIDO
			, SEGUNDO_APELLIDO 				=	V_SEGUNDO_APELLIDO
			, TIPO_DOCUMENTOID_DOCUMENTO	=	V_TIPO_DOCUMENTOID_DOCUMENTO
			, NUMERO_DOCUMENTO 				=	V_NUMERO_DOCUMENTO
            , CARGOID_CARGO					=	V_CARGOID_CARGO
			, EDAD 							=	V_EDAD
			, TELEFONO 						=	V_TELEFONO
			, DIRECCION 					=	V_DIRECCION
			, EMAIL  						= 	V_EMAIL
            , ROLID_ROL						=	V_ROLID_ROL
	WHERE ID_EMPLEADO = P_ID_EMPLEADO;
    
END &
