DELIMITER &
CREATE PROCEDURE PR_ELIMINAR_EMPLEADO( ID_EMPLEADO INT)

BEGIN
	-- Declarar variables
    DECLARE V_ESTADO VARCHAR (30) DEFAULT 'INACTIVO';
	
    -- Elimina registro de la tabla usuario sistema
    UPDATE USUARIO_SISTEMA SET ESTADO = V_ESTADO WHERE EMPLEADOID_EMPLEADO = ID_EMPLEADO;
    
END &
