DELIMITER &
CREATE PROCEDURE PR_ELIMINAR_INVENTARIO( P_ID_INVENTARIO INT)

BEGIN
	-- Declarar variables
    DECLARE V_ESTADO VARCHAR (30) DEFAULT 'INACTIVO';
	
    -- Inactiva el registro de la tabla inventario
    UPDATE INVENTARIO SET ESTADO = V_ESTADO WHERE ID_INVENTARIO = P_ID_INVENTARIO;
    
END &
