DELIMITER &
CREATE PROCEDURE PR_ELIMINAR_PAQUETE(  P_ID_PAQUETE 	INT)

BEGIN
	-- Declarar variables
        DECLARE V_ESTADO  	 VARCHAR (30) DEFAULT 'INACTIVO'; 
	
    -- Se Inactiva el registro
    UPDATE PAQUETE SET ESTADO = V_ESTADO WHERE ID_PAQUETE = P_ID_PAQUETE;


END &