DELIMITER &
CREATE PROCEDURE PR_ACTUALIZAR_PEDIDO( P_ID_PEDIDO INT, P_ESTADO VARCHAR (40))

BEGIN
    -- Declarar variables
    DECLARE V_ID_ESTADO_PEDIDO  					INT		(15) ;
	
    -- Obtener Id del estado pedido
    SELECT ID_ESTADOPEDIDO INTO V_ID_ESTADO_PEDIDO FROM(SELECT ID_ESTADOPEDIDO FROM ESTADO_PEDIDO WHERE ESTADO =P_ESTADO) AS ID_ESTADOPEDIDO;
    
    -- Editar registro de la tabla usuario sistema
    UPDATE PEDIDO 							
		SET   ESTADOPEDIDOID_ESTADOPEDIDO 	=	V_ID_ESTADO_PEDIDO
	WHERE ID_PEDIDO = P_ID_PEDIDO;
    
END &
