DELIMITER &
CREATE PROCEDURE PR_ELIMINAR_USUARIO( ID_USUARIO INT)

BEGIN
	-- Declarar variables
    DECLARE V_ESTADO VARCHAR (30) DEFAULT 'INACTIVO';
	
    -- Elimina registro de la tabla usuario sistema
    UPDATE USUARIO_SISTEMA SET ESTADO = V_ESTADO WHERE USUARIOID_USUARIO = ID_USUARIO;
    
END &
