CREATE PROCEDURE PR_VER_TURNOS()
SELECT 	C.ID_TURNO
        ,FECHA_INICIO_EVENTO
        ,FECHA_FIN_EVENTO
        ,A.ID_EMPLEADO
		,CONCAT(A.PRIMER_NOMBRE, ' ',A.SEGUNDO_NOMBRE, ' ',A.PRIMER_APELLIDO, ' ',A.SEGUNDO_APELLIDO) 	AS NOMBRE
        ,NOMBRE_DE_CARGO
        ,ID_PEDIDO
        ,CIUDAD_EVENTO
        ,BARRIO_EVENTO
        ,DIRECCION_EVENTO
FROM 		EMPLEADO 		AS A
INNER JOIN 	EMPLEADO_TURNO	AS B ON A.ID_EMPLEADO		=	B.EMPLEADOID_EMPLEADO
INNER JOIN	TURNO			AS C ON B.TURNOID_TURNO		=	C.ID_TURNO
INNER JOIN	PEDIDO			AS D ON C.PEDIDOID_PEDIDO	=	D.ID_PEDIDO
INNER JOIN	CARGO			AS E ON A.CARGOID_CARGO		=	E.ID_CARGO
-- WHERE A.ID_EMPLEADO = 1
ORDER BY 1
;