CREATE PROCEDURE PR_VER_EMPLEADOS()
SELECT 	A.ID_EMPLEADO
		,CONCAT(A.PRIMER_NOMBRE, ' ',A.SEGUNDO_NOMBRE) 		AS NOMBRES
		,CONCAT(A.PRIMER_APELLIDO, ' ',A.SEGUNDO_APELLIDO) 	AS APELLIDOS
		,CONCAT(B.SIGLAS,'-',A.NUMERO_DOCUMENTO) 			AS DOCUMENTO
		,A.EDAD
        ,A.TELEFONO
		,A.EMAIL
		,D.NOMBRE_ROL 										AS ROL
        ,E.NOMBRE_DE_CARGO									AS CARGO
		,C.NOMBRE_USUARIO 									AS USUARIO_SISTEMA
		,C.CLAVE
FROM 		EMPLEADO 		AS A
INNER JOIN 	TIPO_DOCUMENTO 	AS B		ON A.Tipo_documentoId_documento = B.id_documento
INNER JOIN 	USUARIO_SISTEMA AS C		ON C.EMPLEADOID_EMPLEADO		= A.ID_EMPLEADO
INNER JOIN 	ROL 			AS D		ON D.id_rol 					= A.rolId_rol
INNER JOIN	CARGO			AS E		ON A.CARGOID_CARGO				= E.ID_CARGO
WHERE C.ESTADO = 'ACTIVO'
;
