DELIMITER &
CREATE PROCEDURE PR_CREAR_USUARIO( P_PRIMER_NOMBRE VARCHAR (40), P_SEGUNDO_NOMBRE VARCHAR (40), P_PRIMER_APELLIDO VARCHAR (40), P_SEGUNDO_APELLIDO VARCHAR (40),
P_TIPO_DOCUMENTOID_DOCUMENTO INT(10), P_NUMERO_DOCUMENTO VARCHAR (20), P_EDAD INT (5), P_TELEFONO BIGINT (20), P_DIRECCION VARCHAR (50), P_EMAIL  VARCHAR (50))

BEGIN
    -- Declarar variables
    DECLARE V_PRIMER_NOMBRE 				VARCHAR (50) DEFAULT UPPER(P_PRIMER_NOMBRE);
    DECLARE V_SEGUNDO_NOMBRE 				VARCHAR (40) DEFAULT UPPER(P_SEGUNDO_NOMBRE); 
    DECLARE V_PRIMER_APELLIDO 				VARCHAR (40) DEFAULT UPPER(P_PRIMER_APELLIDO);
    DECLARE V_SEGUNDO_APELLIDO 				VARCHAR (40) DEFAULT UPPER(P_SEGUNDO_APELLIDO);
	DECLARE V_TIPO_DOCUMENTOID_DOCUMENTO 	INT		(10) DEFAULT UPPER(P_TIPO_DOCUMENTOID_DOCUMENTO);
    DECLARE V_NUMERO_DOCUMENTO 				VARCHAR (20) DEFAULT UPPER(P_NUMERO_DOCUMENTO);
    DECLARE V_EDAD 							INT 	(5)  DEFAULT UPPER(P_EDAD); 
    DECLARE V_TELEFONO 						BIGINT	(20) DEFAULT UPPER(P_TELEFONO);
    DECLARE V_DIRECCION 					VARCHAR (50) DEFAULT UPPER(P_DIRECCION); 
    DECLARE V_EMAIL  						VARCHAR (50) DEFAULT UPPER(P_EMAIL);
    DECLARE V_ROLID_ROL  					INT		(15) DEFAULT 1;
    DECLARE V_ESTADO  						VARCHAR (30) DEFAULT 'ACTIVO';
    DECLARE V_NUMERO_ALEATORIO_USUARIO     	BIGINT	(20);
    DECLARE V_NUMERO_ALEATORIO_CLAVE     	BIGINT	(20);
    DECLARE V_USUARIO_SISTEMA             	VARCHAR (50);
    DECLARE V_ULTIMO_REGISTRO				INT		(10);
    
    -- Generar número aleatorio
    SELECT VALOR_ALEATORIO INTO V_NUMERO_ALEATORIO_USUARIO FROM( SELECT FLOOR(RAND()*(10000-1+1))+1 AS VALOR_ALEATORIO)  AS NUMERO_ALEATORIO_USUARIO;
    SELECT VALOR_ALEATORIO INTO V_NUMERO_ALEATORIO_CLAVE   FROM( SELECT LPAD(FLOOR(RAND()*(100000-1+1))+1,6,0)  AS VALOR_ALEATORIO) AS NUMERO_ALEATORIO_CLAVE;
    
    -- Generar usuario para login
    SELECT USUARIO_SISTEMA INTO V_USUARIO_SISTEMA FROM (SELECT CONCAT(SUBSTRING(V_PRIMER_NOMBRE,1,1),V_PRIMER_APELLIDO,V_NUMERO_ALEATORIO_USUARIO) AS USUARIO_SISTEMA) AS CREAR_USUARIO_SISTEMA;
    
    -- Crea el registro en la tabla usuario
    INSERT INTO USUARIO
    (Id_usuario, Primer_nombre, Segundo_nombre, Primer_apellido, Segundo_apellido, Tipo_documentoId_documento, Numero_documento, Edad, Telefono, Direccion, Email, RolId_rol) 
    VALUES
    (NULL, V_PRIMER_NOMBRE, V_SEGUNDO_NOMBRE, V_PRIMER_APELLIDO, V_SEGUNDO_APELLIDO, V_TIPO_DOCUMENTOID_DOCUMENTO, V_NUMERO_DOCUMENTO, V_EDAD, V_TELEFONO, V_DIRECCION, V_EMAIL, V_ROLID_ROL);
	
    -- Validar ultimo registro en la tabla usuario
    SELECT ULTIMO_ID_USUARIO INTO V_ULTIMO_REGISTRO FROM (select MAX(ID_USUARIO) AS ULTIMO_ID_USUARIO from USUARIO) AS ULTIMO_ID_USUARIO;
    
    -- crear usuario para login
    INSERT INTO USUARIO_SISTEMA
	(Id_Usuariosistema, Nombre_usuario, Clave, Avatar, Estado, UsuarioId_usuario, EmpleadoId_empleado)
	VALUES
	(NULL, V_USUARIO_SISTEMA, V_NUMERO_ALEATORIO_CLAVE, NULL, V_ESTADO, V_ULTIMO_REGISTRO, NULL);
    
END &
