CREATE OR REPLACE VIEW VW_VER_EMPLEADOS
(    ID_EMPLEADO
    ,PRIMER_NOMBRE
    ,SEGUNDO_NOMBRE
    ,PRIMER_APELLIDO
    ,SEGUNDO_APELLIDO
    ,DOCUMENTO
    ,NUMERO_DOCUMENTO
    ,CARGO
    ,EDAD
    ,TELEFONO
    ,DIRECCION
    ,EMAIL
    ,ROL
    ,USUARIO_SISTEMA
    ,CLAVE
    ,RESPUESTA_MODAL
)

AS

SELECT 	A.ID_EMPLEADO
		,A.PRIMER_NOMBRE
        ,A.SEGUNDO_NOMBRE 		
		,A.PRIMER_APELLIDO
        ,A.SEGUNDO_APELLIDO
		,B.SIGLAS											AS DOCUMENTO
        ,A.NUMERO_DOCUMENTO
        ,E.NOMBRE_DE_CARGO									AS CARGO
		,A.EDAD
        ,A.TELEFONO
        ,A.DIRECCION
		,A.EMAIL
		,D.NOMBRE_ROL 										AS ROL
		,C.NOMBRE_USUARIO 									AS USUARIO_SISTEMA
		,C.CLAVE
        ,A.ID_EMPLEADO										AS RESPUESTA_MODAL
FROM 		EMPLEADO 		AS A
INNER JOIN 	TIPO_DOCUMENTO 	AS B		ON A.Tipo_documentoId_documento = B.id_documento
INNER JOIN 	USUARIO_SISTEMA AS C		ON C.EMPLEADOID_EMPLEADO 		= A.ID_EMPLEADO
INNER JOIN 	ROL 			AS D		ON D.id_rol 					= A.rolId_rol
INNER JOIN	CARGO			AS E		ON A.CARGOID_CARGO 				= E.ID_CARGO
WHERE C.ESTADO ='ACTIVO'
;