CREATE OR REPLACE VIEW VW_VER_PAQUETE
(    ID_PAQUETE
		,TIPO_DE_PAQUETE
        ,ID_INVENTARIO
        ,INVENTARIO
)

AS

SELECT 	 ID_PAQUETE
		,TIPO_DE_PAQUETE
        ,ID_INVENTARIO
        ,INVENTARIO
FROM PAQUETE A
INNER JOIN INVENTARIO_PAQUETE	AS B	ON A.ID_PAQUETE						= B.PAQUETEID_PAQUETE
INNER JOIN INVENTARIO			AS C	ON B.INVENTARIOID_INVENTARIO		= C.ID_INVENTARIO
;