CREATE OR REPLACE view vw_pago_preferido
(PAGO_PREFERIDO)
as

SELECT max(PAGO) PAGO_PREFERIDO
FROM(
	select count(ID_PAGO) CANTIDAD
		   ,NOMBRE_PAGO PAGO
	from(
		SELECT PE.ID_PEDIDO
			 , PA.tipo_de_paquete
			 , concat(US.PRIMER_NOMBRE,' ',US.SEGUNDO_NOMBRE) NOMBRES_PAGADOR
			 , concat(US.PRIMER_APELLIDO,' ',US.SEGUNDO_APELLIDO) APELLIDOS_PAGADOR
			 , FA.ID_FACTURA
			 , FA.VALOR_TOTAL
			 , FA.TIPO_DE_FACTURA
			 , PG.ID_PAGO
			 , TP.NOMBRE_PAGO
		FROM PEDIDO PE
		INNER JOIN PAQUETE PA 		ON PA.ID_PAQUETE 		= PE.Paquete_Idpaquete
		INNER JOIN USUARIO US 		ON US.ID_USUARIO 		= PE.USUARIOID_USUARIO
		INNER JOIN FACTURA FA 		ON FA.PedidoId_pedido 	= PE.ID_PEDIDO
		INNER JOIN PAGOS   PG 		ON PG.Usuarioid_usuario = US.ID_USUARIO
		INNER JOIN TIPOS_DE_PAGO TP ON TP.ID_TIPO_PAGO		= PG.TIPOS_DE_PAGOID_TIPO_PAGO
		ORDER BY 1
	) a
	group by NOMBRE_PAGO
	ORDER BY 1 DESC
	) B
	;