CREATE OR REPLACE VIEW VW_VER_PAQUETES_EVENTOS
(    ID_EVENTO
	,TIPO_DE_EVENTO
	,ID_PAQUETE
	,TIPO_DE_PAQUETE
	,CANTIDAD_PERSONAS
    ,VALOR_TOTAL
)

AS

SELECT 	 ID_EVENTO
		,TIPO_DE_EVENTO
		,ID_PAQUETE
		,TIPO_DE_PAQUETE
        ,CANTIDAD_PERSONAS
        ,VALOR_TOTAL
FROM PAQUETE A
INNER JOIN EVENTO				AS D	ON A.EVENTOID_EVENTO 				= D.ID_EVENTO
WHERE A.ESTADO ='ACTIVO'
ORDER BY ID_EVENTO ASC
;