CREATE OR REPLACE VIEW VW_VER_USUARIOS
(    ID_USUARIO
    ,NOMBRES
    ,APELLIDOS
    ,DOCUMENTO
    ,EDAD
    ,TELEFONO
    ,EMAIL
    ,ROL
    ,USUARIO_SISTEMA
    ,CLAVE
)

AS

SELECT 	A.ID_USUARIO
		,CONCAT(A.PRIMER_NOMBRE, ' ',A.SEGUNDO_NOMBRE) 		AS NOMBRES
		,CONCAT(A.PRIMER_APELLIDO, ' ',A.SEGUNDO_APELLIDO) 	AS APELLIDOS
		,CONCAT(B.SIGLAS,'-',A.NUMERO_DOCUMENTO) 			AS DOCUMENTO
		,A.EDAD
        ,A.TELEFONO
		,A.EMAIL
		,D.NOMBRE_ROL 										AS ROL
		,C.NOMBRE_USUARIO 									AS USUARIO_SISTEMA
		,C.CLAVE
FROM 		USUARIO 		AS A
INNER JOIN 	TIPO_DOCUMENTO 	AS B		ON A.Tipo_documentoId_documento = B.id_documento
INNER JOIN 	USUARIO_SISTEMA AS C		ON C.USUARIOID_USUARIO = A.id_usuario
INNER JOIN 	ROL 			AS D		ON D.id_rol = A.rolId_rol
WHERE C.ESTADO ='ACTIVO'
;