CREATE OR REPLACE VIEW VW_VER_INVENTARIO
(
	ID_INVENTARIO
	,INVENTARIO
	,CANTIDAD
	,VALOR_SIN_IVA
	,IVA
	,VALOR_TOTAL
	,CATEGORIA
)
AS

SELECT	ID_INVENTARIO
		,INVENTARIO
        ,CANTIDAD
        ,VALOR_SIN_IVA
        ,IVA
        ,VALOR_TOTAL
        ,CATEGORIA
FROM INVENTARIO
WHERE ESTADO='ACTIVO';