CREATE OR REPLACE view VW_REPORTE_VENTAS
(	 ID_PEDIDO
	,TIPO_DE_PAQUETE
    ,NOMBRES_PAGADOR
    ,APELLIDOS_PAGADOR
    ,ID_FACTURA
    ,VALOR_TOTAL
    ,TIPO_DE_FACTURA
    ,ID_PAGO
    ,NOMBRE_PAGO
    )
AS

SELECT PE.ID_PEDIDO
	 , PA.tipo_de_paquete
     , concat(US.PRIMER_NOMBRE,' ',US.SEGUNDO_NOMBRE) NOMBRES_PAGADOR
     , concat(US.PRIMER_APELLIDO,' ',US.SEGUNDO_APELLIDO) APELLIDOS_PAGADOR
     , FA.ID_FACTURA
     , FA.VALOR_TOTAL
     , FA.TIPO_DE_FACTURA
     , PG.ID_PAGO
     , TP.NOMBRE_PAGO
FROM PEDIDO PE
INNER JOIN PAQUETE PA 		ON PA.ID_PAQUETE 		= PE.Paquete_Idpaquete
INNER JOIN USUARIO US 		ON US.ID_USUARIO 		= PE.USUARIOID_USUARIO
INNER JOIN FACTURA FA 		ON FA.PedidoId_pedido 	= PE.ID_PEDIDO
INNER JOIN PAGOS   PG 		ON PG.Usuarioid_usuario = US.ID_USUARIO
INNER JOIN TIPOS_DE_PAGO TP ON TP.ID_TIPO_PAGO		= PG.TIPOS_DE_PAGOID_TIPO_PAGO
order by 1
;

