CREATE OR REPLACE VIEW VW_VER_PAQUETE
(    ID_EVENTO
	,TIPO_DE_EVENTO
	,ID_PAQUETE
	,TIPO_DE_PAQUETE
    ,ID_INVENTARIO
    ,INVENTARIO
    ,CANTIDAD
    ,VALOR_SIN_IVA
	,IVA
	,VALOR_TOTAL
)

AS

SELECT 	 D.ID_EVENTO
		,D.TIPO_DE_EVENTO
		,A.ID_PAQUETE
		,A.TIPO_DE_PAQUETE
        ,C.ID_INVENTARIO
        ,C.INVENTARIO
        ,B.CANTIDAD
        ,B.VALOR_SIN_IVA
        ,B.IVA
        ,B.VALOR_TOTAL
FROM PAQUETE A
INNER JOIN INVENTARIO_PAQUETE	AS B	ON A.ID_PAQUETE						= B.PAQUETEID_PAQUETE
INNER JOIN INVENTARIO			AS C	ON B.INVENTARIOID_INVENTARIO		= C.ID_INVENTARIO
INNER JOIN EVENTO				AS D	ON A.EVENTOID_EVENTO 				= D.ID_EVENTO
WHERE A.ESTADO ='ACTIVO'
ORDER BY ID_EVENTO ASC
;